import {baseSepolia} from "wagmi/chains"
import {Chain} from "@rainbow-me/rainbowkit"

// you can add supported or new chains using the relevant viem chain
// or by using `defineChain` from viem
export const supportedChains: Array<Chain>= [baseSepolia];

export const CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_CONTRACT_ADDRESS as `0x${string}`;

export const CONTRACT_ABI = [
   {
      "type":"constructor",
      "inputs":[
         {
            "name":"_randomnessSender",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"DEFAULT_CALLBACK_GAS_LIMIT",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint32",
            "internalType":"uint32"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"MAX_PARTICIPANTS",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"MAX_WINNERS",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"MIN_PARTICIPANTS",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"acceptOwnership",
      "inputs":[
         
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"cancelSelection",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"createSubscriptionAndFundNative",
      "inputs":[
         
      ],
      "outputs":[
         
      ],
      "stateMutability":"payable"
   },
   {
      "type":"function",
      "name":"emergencyWithdraw",
      "inputs":[
         
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"getBalance",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getSelection",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"tuple",
            "internalType":"struct ProvablyFairLaunchpad.SelectionRequest",
            "components":[
               {
                  "name":"requester",
                  "type":"address",
                  "internalType":"address"
               },
               {
                  "name":"participants",
                  "type":"address[]",
                  "internalType":"address[]"
               },
               {
                  "name":"winnerCount",
                  "type":"uint256",
                  "internalType":"uint256"
               },
               {
                  "name":"requestId",
                  "type":"uint256",
                  "internalType":"uint256"
               },
               {
                  "name":"isCompleted",
                  "type":"bool",
                  "internalType":"bool"
               },
               {
                  "name":"isCancelled",
                  "type":"bool",
                  "internalType":"bool"
               },
               {
                  "name":"winners",
                  "type":"address[]",
                  "internalType":"address[]"
               },
               {
                  "name":"randomness",
                  "type":"bytes32",
                  "internalType":"bytes32"
               },
               {
                  "name":"timestamp",
                  "type":"uint256",
                  "internalType":"uint256"
               }
            ]
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getWinners",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"address[]",
            "internalType":"address[]"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"isInFlight",
      "inputs":[
         {
            "name":"requestId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"bool",
            "internalType":"bool"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"nextSelectionId",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"owner",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"pendingRequestExists",
      "inputs":[
         {
            "name":"subId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"bool",
            "internalType":"bool"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"randomnessSender",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"receiveRandomness",
      "inputs":[
         {
            "name":"requestID",
            "type":"uint256",
            "internalType":"uint256"
         },
         {
            "name":"randomness",
            "type":"bytes32",
            "internalType":"bytes32"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"requestIdToSelectionId",
      "inputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"requestSelection",
      "inputs":[
         {
            "name":"participants",
            "type":"address[]",
            "internalType":"address[]"
         },
         {
            "name":"winnerCount",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"payable"
   },
   {
      "type":"function",
      "name":"selections",
      "inputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"requester",
            "type":"address",
            "internalType":"address"
         },
         {
            "name":"participants",
            "type":"address[]",
            "internalType":"address[]"
         },
         {
            "name":"winnerCount",
            "type":"uint256",
            "internalType":"uint256"
         },
         {
            "name":"requestId",
            "type":"uint256",
            "internalType":"uint256"
         },
         {
            "name":"isCompleted",
            "type":"bool",
            "internalType":"bool"
         },
         {
            "name":"isCancelled",
            "type":"bool",
            "internalType":"bool"
         },
         {
            "name":"winners",
            "type":"address[]",
            "internalType":"address[]"
         },
         {
            "name":"randomness",
            "type":"bytes32",
            "internalType":"bytes32"
         },
         {
            "name":"timestamp",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"setRandomnessSender",
      "inputs":[
         {
            "name":"_randomnessSender",
            "type":"address",
            "internalType":"address"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"setSubId",
      "inputs":[
         {
            "name":"subId",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"subscriptionId",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"topUpSubscriptionNative",
      "inputs":[
         
      ],
      "outputs":[
         
      ],
      "stateMutability":"payable"
   },
   {
      "type":"function",
      "name":"transferOwnership",
      "inputs":[
         {
            "name":"to",
            "type":"address",
            "internalType":"address"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"updateSubscription",
      "inputs":[
         {
            "name":"consumers",
            "type":"address[]",
            "internalType":"address[]"
         }
      ],
      "outputs":[
         
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"verifyFairness",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "internalType":"uint256"
         },
         {
            "name":"expectedWinners",
            "type":"address[]",
            "internalType":"address[]"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"bool",
            "internalType":"bool"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"event",
      "name":"Funded",
      "inputs":[
         {
            "name":"sender",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"amount",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"NewSubscriptionId",
      "inputs":[
         {
            "name":"subscriptionId",
            "type":"uint256",
            "indexed":true,
            "internalType":"uint256"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"OwnershipTransferRequested",
      "inputs":[
         {
            "name":"from",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"to",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"OwnershipTransferred",
      "inputs":[
         {
            "name":"from",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"to",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"Received",
      "inputs":[
         {
            "name":"",
            "type":"address",
            "indexed":false,
            "internalType":"address"
         },
         {
            "name":"",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"SelectionCancelled",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "indexed":true,
            "internalType":"uint256"
         },
         {
            "name":"requester",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"requestId",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"SelectionCompleted",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "indexed":true,
            "internalType":"uint256"
         },
         {
            "name":"requester",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"winners",
            "type":"address[]",
            "indexed":false,
            "internalType":"address[]"
         },
         {
            "name":"requestId",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         },
         {
            "name":"randomness",
            "type":"bytes32",
            "indexed":false,
            "internalType":"bytes32"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"SelectionRequested",
      "inputs":[
         {
            "name":"selectionId",
            "type":"uint256",
            "indexed":true,
            "internalType":"uint256"
         },
         {
            "name":"requester",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"participantCount",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         },
         {
            "name":"winnerCount",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         },
         {
            "name":"requestId",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         }
      ],
      "anonymous":false
   },
   {
      "type":"event",
      "name":"Withdrawn",
      "inputs":[
         {
            "name":"recipient",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"amount",
            "type":"uint256",
            "indexed":false,
            "internalType":"uint256"
         }
      ],
      "anonymous":false
   },
   {
      "type":"error",
      "name":"DuplicateParticipants",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"InsufficientRandomness",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"InvalidParticipantCount",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"InvalidRequestId",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"InvalidWinnerCount",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"NotAuthorized",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"SelectionAlreadyCancelled",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"SelectionAlreadyCompleted",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"SelectionNotCompleted",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"SelectionNotFound",
      "inputs":[
         
      ]
   },
   {
      "type":"error",
      "name":"ZeroAddressParticipant",
      "inputs":[
         
      ]
   }
]